// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "valhalla": helse Resource Client
//
// Command:
// $ goagen
// --design=github.com/waymobetta/valhalla-api/design
// --out=$(GOPATH)/src/github.com/waymobetta/valhalla-api
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// VisHelsePath computes a request path to the vis action of helse.
func VisHelsePath() string {

	return fmt.Sprintf("/v1/helse")
}

// OK hvis sunn
func (c *Client) VisHelse(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewVisHelseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewVisHelseRequest create the request corresponding to the vis action endpoint of the helse resource.
func (c *Client) NewVisHelseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
